### ISSUE TITLE
v7: `useNavigate()` may be used only in the context of a `<Router>` component

### ISSUE THREAD

**Issue by LekoArts** [remix-run/react-router#12399]
### I'm using React Router as a...

framework

### Reproduction

https://github.com/lekoarts-demos/react-router-use-navigate-bug

For the reproduction to run you'll need a Clerk account to generate a pair of publishable key/secret key. On your Discord we have a shared channel with Clerk where I could also share credentials if you want, I didn't want to put them into a public repository.

### System Info

```shell
System:
    OS: macOS 15.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 101.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/Library/Caches/fnm_multishells/90793_1732613658873/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/90793_1732613658873/bin/yarn
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/90793_1732613658873/bin/npm
    pnpm: 9.14.2 - ~/Library/Caches/fnm_multishells/90793_1732613658873/bin/pnpm
    bun: 1.1.18 - ~/.bun/bin/bun
  Browsers:
    Chrome: 131.0.6778.86
    Safari: 18.1
  npmPackages:
    @react-router/dev: 7.0.1 => 7.0.1
    @react-router/node: 7.0.1 => 7.0.1
    @react-router/serve: 7.0.1 => 7.0.1
    react-router: 7.0.1 => 7.0.1
    vite: ^5.4.11 => 5.4.11
```

### Used Package Manager

pnpm

### Expected Behavior

Hello!

I'm working for [Clerk](https://clerk.com/) and I'm currently in the process of adding an SDK for React Router (we have an existing one for [Remix](https://clerk.com/docs/quickstarts/remix)). My WIP PR is here: https://github.com/clerk/javascript/pull/4621

Unfortunately, I'm running into a problem with our current setup where I get the error:

```shell
Error: useNavigate() may be used only in the context of a <Router> component.
```

The stacktrace leads to a custom hook in our SDK that uses `useNavigate()`. Our `<ClerkProvider>` (that uses that hook) is used inside the `root.tsx` file and wrapping the `<Outlet />`.

In the commit https://github.com/lekoarts-demos/react-router-use-navigate-bug/commit/ede06038650418835394f6592c6d12098fe91597 of the reproduction repository you can see the expected behavior. You use the `<ClerkProvider>` and our components/hooks have access to the `react-router` hooks.

### Actual Behavior

Unfortunately, the only way I got it to work was like this:

https://github.com/lekoarts-demos/react-router-use-navigate-bug/blob/783c37fb93f02baadf15103eddbaa91ca78fd9ce/app/root.tsx#L64-L79

By manually passing the hooks (or their return values) through the provider into our components. You can browse the reproduction value between the states of "actual behavior" and "expected behavior".

I've found https://github.com/remix-run/react-router/issues/12368 and https://github.com/remix-run/react-router/issues/11016 but `pnpm ls react-router` shows that only one instance of `react-router` is used. Our SDK only defines it as a peerDependency.

**Comment by RMCampos** [comment]
Having the very same issue.

## System Info
```
System:
    OS: Windows 11 Pro
    CPU: AMD Ryzen 5 3450U
    Memory: 24.0GB
    Shell: 5.2.15 - /bin/bash (inside WSL2)
  Binaries:
    Node: 22.11.0
    npm: 10.9.1
  Browsers:
    Firefox: 133.0 (64-bit)
  npmPackages:
    react-router-dom: ^7.0.1
    vite: ^5.4.11
```

**Comment by RMCampos** [comment]
Having the very same issue.

## System Info
```
System:
    OS: Windows 11 Pro
    CPU: AMD Ryzen 5 3450U
    Memory: 24.0GB
    Shell: 5.2.15 - /bin/bash (inside WSL2)
  Binaries:
    Node: 22.11.0
    npm: 10.9.1
  Browsers:
    Firefox: 133.0 (64-bit)
  npmPackages:
    react-router-dom: ^7.0.1
    vite: ^5.4.11
```

**Comment by brookslybrand** [comment]
It looks like `react-router` has a `development` and `production` bundle for. For some reason when `@clerk/react-router` imports `useNavigate` it's using the `production` one, which is why it's not finding a `<Router>` because the context identifier it's looking for is different.

Whether or not this an issue with how we've setup the packages or is something that can easily be resolved by how you're setting up the `@clerk/react-router` package, I don't know. At this point it's a bit outside my knowledge, so I'll pass it along to the team

**Comment by LekoArts** [comment]
For my reproduction repository above (and another testing site) the PR https://github.com/remix-run/react-router/pull/12437 resolved our problem described in this issue.

I know it's a stopgap but it works. So feel free to close the issue 👍

**Comment by brookslybrand** [comment]
Perfect, thanks @LekoArts for helping identify the issue. Now that we know to look for it we _shouldn't_ have a regression, but if we ever do please reach out 🙏

Resolved by #12437

**Comment by acelaya** [comment]
I see this was closed, but I'm still experimenting this issue with react-router 7.0.2

Surprisingly, it happens only with node 23.x, but works as expected with 20.x and 22.x

**Comment by brookslybrand** [comment]
> I see this was closed, but I'm still experimenting this issue with react-router 7.0.2
> 
> Surprisingly, it happens only with node 23.x, but works as expected with 20.x and 22.x

Yep, I am also surprised by this. I opened #12475 last week and the team is aware.

**Comment by linkm-ampere** [comment]
Seeing this with
react-router @7.0.2
nodejs @20.18.1
also running on latest macos, if that matters.

seems to be still a problem when accessing the hook from a component.

**Comment by johncmacy** [comment]
I'm also seeing this, with:

```
System:
    OS: macOS 15.1.1
  Binaries:
    Node: 22.12.0
  npmPackages:
    @clerk/react-router: ^0.1.1 => 0.1.1
    @react-router/dev: ^7.0.0 => 7.0.2 
    @react-router/node: ^7.0.0 => 7.0.2 
    @react-router/serve: ^7.0.0 => 7.0.2
    vite: ^5.1.0 => 5.4.11
```

**Comment by ZeldOcarina** [comment]
> Perfect, thanks @LekoArts for helping identify the issue. Now that we know to look for it we _shouldn't_ have a regression, but if we ever do please reach out 🙏
> 
> Resolved by #12437

Can we reopen this too?

**Comment by brookslybrand** [comment]
@ZeldOcarina I'm going to keep this one closed since we have #12475 open now to track this issue

**Comment by ZeldOcarina** [comment]
Got it thanks! :)

**Comment by tomachinz** [comment]
> PR [#12437](https://github.com/remix-run/react-router/pull/12437) resolved our problem described in this issue.
> I know it's a stopgap but it works. So feel free to close the issue 👍

Erm. Been trying to figure this out for ages.

**Comment by Data5tream** [comment]
We had the same issue when trying to use [nuqs](https://github.com/47ng/nuqs).
Turned out that we had different versions of react packages (some were at 7.6.0, some at 7.6.2). Upgrading all to the exact same version (7.6.2 in our case) solved the issue.

**Comment by sarifmiaa** [comment]
> We had the same issue when trying to use [nuqs](https://github.com/47ng/nuqs). Turned out that we had different versions of react packages (some were at 7.6.0, some at 7.6.2). Upgrading all to the exact same version (7.6.2 in our case) solved the issue.

I recently faced the same issue. Make sure that React, React DOM, and React Router are all using the exact same version—this fixed it for me.

**Comment by ZakeriaHirsi** [comment]
> We had the same issue when trying to use [nuqs](https://github.com/47ng/nuqs). Turned out that we had different versions of react packages (some were at 7.6.0, some at 7.6.2). Upgrading all to the exact same version (7.6.2 in our case) solved the issue.

+1 to the above. For us there was a mismatch in react-router versions for dependencies and devDependencies in the package.json. This meant that it worked in prod but not for local development, updating them to the same version worked
